parameters:
  name: ''
  vmImage: ''
  cmakeArgs: ''

jobs:
  - job: ${{ parameters.name }}
    strategy:
      matrix:
        REL:
          BUILD_TYPE: Release
        DBG:
          BUILD_TYPE: Debug
        RELDBG:
          BUILD_TYPE: RelWithDebInfo
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - task: CMake@1
      displayName: 'CMake'
      inputs:
        cmakeArgs: ${{ parameters.cmakeArgs }}
    - task: MSBuild@1
      displayName: 'Build Solution'
      inputs:
        solution: build/cista.sln
        msbuildArguments: '/m /p:Configuration=$(BUILD_TYPE)'
    - powershell: |
        echo "RUN 1"
        .\cista-test
        echo "RUN 2"
        .\cista-test
        echo "RUN 3"
        .\cista-test
        echo "RUN 4"
        .\cista-test
        echo "RUN 5"
        .\cista-test
      displayName: 'Run Tests'
      errorActionPreference: continue
      workingDirectory: build\$(BUILD_TYPE)